#!/usr/bin/lua

local uci = require('simple-uci').cursor()

local branch = uci:get('autoupdater', 'settings', 'branch')

if branch == 'beta' then
  uci:set('autoupdater', 'settings', 'branch', 'testing')
end

if uci:get('autoupdater', 'beta') then
  uci:delete('autoupdater', 'beta')
end

uci:save('autoupdater')
